export const CustomTypography = {
    "display-2xl-regular": {
      fontSize: "72px",
      lineHeight: "90px",
      fontKerning: "0%",
      fontWeight: 400,
      letterSpacing: "",
      fontFamily: "Inter",
    },
    "display-2xl-medium": {
      fontSize: "72px",
      lineHeight: "90px",
      fontKerning: "0%",
      fontWeight: 500,
      letterSpacing: "",
      fontFamily: "Inter",
    },
    "display-2xl-semibold": {
      fontSize: "72px",
      lineHeight: "90px",
      fontKerning: "0%",
      fontWeight: 600,
      letterSpacing: "",
      fontFamily: "Inter",
    },
    "display-2xl-bold": {
      fontSize: "72px",
      lineHeight: "90px",
      fontKerning: "0%",
      fontWeight: 700,
      letterSpacing: "",
      fontFamily: "Inter",
    },
    "display-xl-regular": {
      fontSize: "60px",
      lineHeight: "72px",
      fontKerning: "0%",
      fontWeight: 400,
      letterSpacing: "",
      fontFamily: "Inter",
    },
  
    "display-xl-medium": {
      fontSize: "60px",
      lineHeight: "72px",
      fontKerning: "0%",
      fontWeight: 500,
      letterSpacing: "",
      fontFamily: "Inter",
    },
    "display-xl-semibold": {
      fontSize: "60px",
      lineHeight: "72px",
      fontKerning: "0%",
      fontWeight: 600,
      letterSpacing: "",
      fontFamily: "Inter",
    },
    "display-xl-bold": {
      fontSize: "60px",
      lineHeight: "72px",
      fontKerning: "0%",
      fontWeight: 700,
      fontFamily: "Inter",
      letterSpacing: "",
    },
  
    "display-lg-regular": {
      fontSize: "48px",
      lineHeight: "60px",
      fontKerning: "0%",
      fontWeight: 400,
      letterSpacing: "",
      fontFamily: "Inter",
    },
    "display-lg-medium": {
      fontSize: "48px",
      lineHeight: "60px",
      fontKerning: "0%",
      fontWeight: 500,
      letterSpacing: "",
      fontFamily: "Inter",
    },
    "display-lg-semibold": {
      fontSize: "48px",
      lineHeight: "60px",
      fontKerning: "0%",
      fontWeight: 600,
      letterSpacing: "",
      fontFamily: "Inter",
    },
    "display-lg-bold": {
      fontSize: "48px",
      lineHeight: "60px",
      fontKerning: "0%",
      fontWeight: 700,
      fontFamily: "Inter",
      letterSpacing: "",
    },
    "display-md-regular": {
      fontSize: "36px",
      lineHeight: "44px",
      fontKerning: "0%",
      fontWeight: 400,
      fontFamily: "Inter",
      letterSpacing: "",
    },
    "display-md-medium": {
      fontSize: "36px",
      lineHeight: "44px",
      fontKerning: "0%",
      fontWeight: 500,
      letterSpacing: "",
      fontFamily: "Inter",
    },
    "display-md-semibold": {
      fontSize: "36px",
      lineHeight: "44px",
      fontKerning: "0%",
      fontWeight: 600,
      letterSpacing: "",
      fontFamily: "Inter",
    },
    "display-md-bold": {
      fontSize: "36px",
      lineHeight: "44px",
      fontKerning: "0%",
      fontWeight: 700,
      letterSpacing: "",
      fontFamily: "Inter",
    },
    "display-sm-regular": {
      fontSize: "30px",
      lineHeight: "38px",
      fontKerning: "0%",
      fontWeight: 400,
      fontFamily: "Inter",
      letterSpacing: "",
    },
    "display-sm-medium": {
      fontSize: "30px",
      lineHeight: "38px",
      fontKerning: "0%",
      fontWeight: 500,
      letterSpacing: "",
      fontFamily: "Inter",
    },
    "display-sm-semibold": {
      fontSize: "30px",
      lineHeight: "38px",
      fontKerning: "0%",
      fontWeight: 600,
      letterSpacing: "",
      fontFamily: "Inter",
    },
    "display-sm-bold": {
      fontSize: "30px",
      lineHeight: "38px",
      fontKerning: "0%",
      fontWeight: 700,
      letterSpacing: "",
      fontFamily: "Inter",
    },
  
    "display-xs-regular": {
      fontSize: "24px",
      lineHeight: "40px",
      fontKerning: "0%",
      fontWeight: 400,
      fontFamily: "Inter",
      letterSpacing: "",
    },
    "display-xs-medium": {
      fontSize: "24px",
      lineHeight: "32px",
      fontKerning: "0%",
      fontWeight: 500,
      letterSpacing: "",
      fontFamily: "Inter",
    },
    "display-xs-semibold": {
      fontSize: "24px",
      lineHeight: "40px",
      fontKerning: "0%",
      fontWeight: 600,
      letterSpacing: "",
      fontFamily: "Inter",
    },
    "display-xs-bold": {
      fontSize: "24px",
      lineHeight: "40px",
      fontKerning: "0%",
      fontWeight: 700,
      letterSpacing: "",
      fontFamily: "Inter",
    },
    "display-xs": {
      fontSize: "22px",
      lineHeight: "48px",
      fontKerning: "0%",
      fontWeight: 400,
      letterSpacing: "",
      fontFamily: "Inter",
    },
    "display-xs-response": {
      fontSize: "20px",
      lineHeight: "32px",
      fontWeight: 300,
      letterSpacing: "",
      fontFamily: "Inter",
    },
    "display-xs-response-bold": {
      fontSize: "20px",
      lineHeight: "32px",
      fontWeight: 600,
      letterSpacing: "",
      fontFamily: "Inter",
    },
    "text-xl-regular": {
      fontSize: "20px",
      lineHeight: "30px",
      fontKerning: "0%",
      fontWeight: 400,
      letterSpacing: "",
      fontFamily: "Inter",
    },
    "text-xl-medium": {
      fontSize: "20px",
      lineHeight: "30px",
      fontKerning: "0%",
      fontWeight: 500,
      letterSpacing: "",
      fontFamily: "Inter",
    },
    "text-xl-semibold": {
      fontSize: "20px",
      lineHeight: "30px",
      fontKerning: "0%",
      fontWeight: 600,
      letterSpacing: "",
      fontFamily: "Inter",
    },
    "text-xl-bold": {
      fontSize: "20px",
      lineHeight: "30px",
      fontKerning: "0%",
      fontWeight: 700,
      letterSpacing: "",
      fontFamily: "Inter",
    },
    "text-lg-regular": {
      fontSize: "18px",
      lineHeight: "28px",
      fontKerning: "0%",
      fontWeight: 400,
      letterSpacing: "",
      fontFamily: "Inter",
    },
    "text-lg-medium": {
      fontSize: "18px",
      lineHeight: "28px",
      fontKerning: "0%",
      fontWeight: 500,
      letterSpacing: "",
      fontFamily: "Inter",
    },
    "text-lg-semibold": {
      fontSize: "18px",
      lineHeight: "28px",
      fontKerning: "0%",
      fontWeight: 600,
      letterSpacing: "",
      fontFamily: "Inter",
    },
    "text-lg-bold": {
      fontSize: "18px",
      lineHeight: "28px",
      fontKerning: "0%",
      fontWeight: 700,
      fontFamily: "Inter",
      letterSpacing: "",
    },
    "text-md-regular": {
      fontSize: "16px",
      lineHeight: "24px",
      fontKerning: "0%",
      fontWeight: 400,
      letterSpacing: "",
      fontFamily: "Inter",
    },
    "text-md-medium": {
      fontSize: "16px",
      lineHeight: "24px",
      fontKerning: "0%",
      fontWeight: 500,
      letterSpacing: "",
      fontFamily: "Inter",
    },
    "text-md-semibold": {
      fontSize: "16px",
      lineHeight: "24px",
      fontKerning: "0%",
      fontWeight: 600,
      fontFamily: "Inter",
      letterSpacing: "",
    },
    "text-md-bold": {
      fontSize: "16px",
      lineHeight: "24px",
      fontKerning: "0%",
      fontWeight: 700,
      letterSpacing: "",
      fontFamily: "Inter",
    },
  
    "text-sm-regular": {
      fontSize: "14px",
      lineHeight: "20px",
      fontKerning: "0%",
      fontWeight: 400,
      letterSpacing: "",
      fontFamily: "Inter",
    },
    "text-sm-medium": {
      fontSize: "14px",
      lineHeight: "20px",
      fontKerning: "0%",
      fontWeight: 500,
      letterSpacing: "",
      fontFamily: "Inter",
    },
    "text-sm-semibold": {
      fontSize: "14px",
      lineHeight: "20px",
      fontKerning: "0%",
      fontWeight: 600,
      letterSpacing: "",
      fontFamily: "Inter",
    },
    "text-sm-bold": {
      fontSize: "14px",
      lineHeight: "20px",
      fontKerning: "0%",
      fontWeight: 700,
      letterSpacing: "",
      fontFamily: "Inter",
    },
    "text-sm": {
      fontSize: "13px",
      fontWeight: 400,
      lineHeight: "19.5px",
      fontFamily: "Inter",
    },
    "text-xs-small": {
      fontSize: "12px",
      lineHeight: "14px",
      fontKerning: "0%",
      fontWeight: 300,
      letterSpacing: "",
      fontFamily: "Inter",
    },
    "text-xs-regular": {
      fontSize: "12px",
      lineHeight: "14px",
      fontKerning: "0%",
      fontWeight: 400,
      letterSpacing: "",
      fontFamily: "Inter",
    },
    "text-xs-medium": {
      fontSize: "12px",
      lineHeight: "15.6px",
      fontKerning: "0%",
      fontWeight: 500,
      letterSpacing: "",
      fontFamily: "Inter",
    },
    "text-xs-semibold": {
      fontSize: "12px",
      lineHeight: "15.6px",
      fontKerning: "0%",
      fontWeight: 600,
      letterSpacing: "",
      fontFamily: "Inter",
    },
    "text-xs-bold": {
      fontSize: "12px",
      lineHeight: "15.6px",
      fontKerning: "0%",
      fontWeight: 700,
      letterSpacing: "",
      fontFamily: "Inter",
    },
    "text-xxs-small": {
      fontSize: "10px",
      lineHeight: "14px",
      fontKerning: "0%",
      fontWeight: 300,
      letterSpacing: "",
      fontFamily: "Inter",
    },
    "text-xs": {
      fontSize: "11px",
      fontWeight: 400,
      lineHeight: "15.4px",
      fontFamily: "Inter",
    },
    "text-xxs-medium": {
      fontSize: "10px",
      lineHeight: "12px",
      fontKerning: "0%",
      fontWeight: 500,
      letterSpacing: "",
      fontFamily: "Inter",
    },
    "text-xxs-semi-bold": {
      fontSize: "10px",
      lineHeight: "12px",
      fontKerning: "0%",
      fontWeight: 600,
      letterSpacing: "",
      fontFamily: "Inter",
    },
    "text-xxs-bold": {
      fontSize: "10px",
      lineHeight: "26px",
      fontKerning: "0%",
      fontWeight: 700,
      letterSpacing: "",
    },
    "text-xxs-regular": {
      fontSize: "11px",
      lineHeight: "15.4px",
      fontKerning: "0%",
      fontWeight: 400,
      letterSpacing: "",
    },
  };
  