import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MuiThemeProvider from "@/theme/provider";
import AppLayout from "@/common/appLayout";
import ClientProvider from "@/components/ClientProvider";
import QueryProvider from "@/components/QueryProvider";
import SessionProviders from "@/components/SessionProviders";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ZeeInvoices",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <SessionProviders>
        <MuiThemeProvider>
          <ClientProvider>
            <QueryProvider>              
            <AppLayout>{children}</AppLayout>           
            </QueryProvider>
          </ClientProvider>
        </MuiThemeProvider>
        </SessionProviders>
      </body>
    </html>
  );
}
