export const icons = {
  logo: "/Images/logos/main-logo.svg",
  whiteLogo: "/Images/logos/white-logo.svg",
  twitter: "/Images/logos/twitter.svg",
  instagarm: "/Images/logos/instagram.svg",
  facebook: "/Images/logos/facebook.svg",
  uploadLogo: "/Images/icons/upload-logo.svg",
  arrowDownIcon: "/Images/icons/arrow-down.svg",
  sendSqaureIcon: "/Images/icons/send-sqaure.svg",
  printIconIcon: "/Images/icons/printer-icon.svg",
  addCircleIcon: "/Images/icons/add-circle.svg",
  addCircleOutlinedIcon: "/Images/icons/add-circle-outlined.svg",
  tickIcon: "/Images/icons/tick-icon.svg",
  colorPickerPaletteIcon: "/Images/icons/color-picker-palette-icon.svg",
  invoiceIcon: "/Images/icons/invoice-icon.svg",
  clientsIcon: "/Images/icons/clients-icon.svg",
  settingsIcon: "/Images/icons/settings-icon.svg",
  firstInvoiceIcon: "/Images/icons/crt-first-invoice-icon.svg",
  searchIcon: "/Images/icons/search-icon.svg",
  filterIcon: "/Images/icons/filter-icon.svg",
  plusIcon: "/Images/icons/plus-icon.svg",
  threeDotsIcon: "/Images/icons/three-dots-icon.svg",
  editIcon: "/Images/icons/edit-icon.svg",
  profileIcon: "/Images/icons/profile-icon.svg",
  logoutIcon: "/Images/icons/logout-icon.svg",
  viewIcon: "/Images/icons/view-icon.svg",
  deleteIcon: "/Images/icons/delete-icon.svg",
  deleteRedIcon: "/Images/icons/delete-Red-icon.svg",
  watermarkIcon: "/Images/icons/watermark-icon.svg",
};

export const backendURL =
  process.env.REACT_APP_BACKEND_URL || "http://localhost:3005";